### ISSUE TITLE
"Store"-Button in default color

### ISSUE THREAD

**Issue by Choppel** [OpenSourcePKG/findnow_tbplugin#10]
Please recheck if it's possible to change the color of the "Store"-Button. If it's easy (like 5 minute work) then fix the option in the settings (currently does nothing). If it's not easily realizable please remove this option completely from the settings.

It was not used in production anyway, only once after the installation with the customer to visually show where the button is. This is now also possible via the icon.

**Comment by stefanwerfling** [comment]
Is removed.
