### ISSUE TITLE
Add a hint to the subdirectory setting to explain how the feature works

### ISSUE THREAD

**Issue by Choppel** [OpenSourcePKG/findnow_tbplugin#12]
Changing the subdirectory in the setting does not seem to do anything.

**Comment by stefanwerfling** [comment]
How was it tested? The option does not create the subdirectory, but was always intended to be used if the directory exists, which is then used for path building

**Comment by Choppel** [comment]
OK. I wasn't aware of that. Its fine how it works.
But in the future we should include a help text in the settings (e.g. small question mark icon with hover text)
