### ISSUE TITLE
File create date should be now, not the date of the mail itself

### ISSUE THREAD

**Issue by Choppel** [OpenSourcePKG/findnow_tbplugin#13]
As the title suggests, the file creation date is programmatically set to the date of the eMail. This seems counterintuitive. It may be important (e.g. for archiving purposes) to know when the file was actually saved to disk by a person via the plugin. Using the mail date, which could be way back in the past, would be wrong in this instance.

**Comment by stefanwerfling** [comment]
It depends. It was already like that in the old version. Because this date is used in the FindNow search engine if the date is not included in the file name. Wouldn't it be better to have an option here?

**Comment by Choppel** [comment]
Is there a way to not have the date in the filename when storing mails via this plugin?
Because, if every stored eMail always has its date prepended to the file name, there is no use to reflect the same date in the metadata of the file. FindNow will find the mail based on this date regardless.
It would be better in this case to reflect the two different dates. The "original" date when the eMail was received based on EML metadata and the date the user exported the mail (which is an almost clear indicator that the eMail was read or at least recognized by the user).

The described algorithm in FindNow does not have to change and always seemed compatible with this procedure.

**Comment by stefanwerfling** [comment]
I just wanted to remember how the basic thought. We can remove the date of the file from the email and see how it goes.

**Comment by Choppel** [comment]
Yes. Please change this as described above.

**Comment by stefanwerfling** [comment]
The setting of the date has been removed.
