### ISSUE TITLE
Add a visual cue when saving the settings

### ISSUE THREAD

**Issue by Choppel** [OpenSourcePKG/findnow_tbplugin#17]
Something like an animation on the save button or a small dialog like "Settings successfully saved".

**Comment by stefanwerfling** [comment]
As just discussed, we will adopt the Thunderbird logic. Each element responds to “onChange” and immediately triggers a save. The save button is removed.

**Comment by stefanwerfling** [comment]
Have changed.

**Comment by stefanwerfling** [comment]
I have now checked all inputs, checkboxes and browse buttons. All fields have now been saved. The button now also reacts to saving, first it places the selection in the input and then saving is executed.
