### ISSUE TITLE
Order of the dialogs seems counterintuitive

### ISSUE THREAD

**Issue by Choppel** [OpenSourcePKG/findnow_tbplugin#18]
Currently, when storing a file, the dialog to choose the destination is shown before the dialog for the extra settings. I think its more plausible if the two dialogs were swapped.

**Comment by stefanwerfling** [comment]
Modified sequence:
- Test 1 with Subject Edit Dialog: First came the Subject Edit dialog, then the Save where dialog.
- Test 2 without Subject Edit dialog: Only the dialog with Save where appears.
