### ISSUE TITLE
Thunderbird version Min-Max

### ISSUE THREAD

**Issue by stefanwerfling** [OpenSourcePKG/findnow_tbplugin#19]
Check and work on which thunderbird version Min-Max the new API runs on.

**Comment by stefanwerfling** [comment]
Old Version 78.0 - 102.*

There are several steps for API 111, 113, 115 updates.

Stable, 91, 103, 115 are listed below.

My recommendation would be to support 115 - 115.* directly.

Should be discussed again.

**Comment by Choppel** [comment]
We should only support 115-115.* as you recommend. Every older version is not supported anyway. The users can and should always update to new newest version.
As seen on the Firefox release calendar (which Thunderbird adheres to) the current ESR release is 115. Every year there will be a new main ESR version. The next will be 128. As soon as 128.0 is available we should test the plugin until 128.3 is released. So theoretically we have time from 2024-07-09 until 2024-10-01 to adjust the plugin should that be needed.
