### ISSUE TITLE
Choosing a default directory does not always work

### ISSUE THREAD

**Issue by Choppel** [OpenSourcePKG/findnow_tbplugin#20]
Reproduction
- activate the first settings option (default directory)
- choose a directory via the button → the directory is correctly shown in the input field
- choose a different directory via the button → the directory is still correctly shown in the input field
- edit the input field to point to some directory (valid or not doesn't matter)
- choose a directory via the button → the directory is now NOT correctly shown in the input field

After closing the settings dialog and reopening it, the settings work as expected until the points above are done in order again.

**Comment by stefanwerfling** [comment]
`.setAttribute('value', path);`

setAttribute no longer sets the correct path (the path variable is correct in the debugger), and removing value does not work either.

:O

**Comment by stefanwerfling** [comment]
Further testing and research shows that “setAttribute” for “value” only works the first time and many people have a problem with it. However, setting the property “value” directly works. I changed it for all text input fields.

Test: Entering the wrong directory several times and then selecting it again with the "Browse" dialog. Works now.
