### ISSUE TITLE
Empty value in "abbreviation" setting produces double whitespace in filename

### ISSUE THREAD

**Issue by Choppel** [OpenSourcePKG/findnow_tbplugin#28]

**Comment by Choppel** [comment]
Still an error. I hit the checkbox for "abbreviation" and let the field be empty. When storing a file the filename is e.g. "2023-08-07  Testbetreff-4.eml" which has two spaces between "...07" and "Test..."

**Comment by stefanwerfling** [comment]
Have it tested, now we check abbreviation, is this an empty string we not build with template string.
