### ISSUE TITLE
Submitting version 3.2, further switching to the API.

### ISSUE THREAD

**Issue by stefanwerfling** [OpenSourcePKG/findnow_tbplugin#30]
Hello,

Your add-on, FindNow 3.2, has been reviewed and did not meet the criteria for being hosted in our gallery.

Reviewer:
John Bieling

Comments:
These versions are being rejected due to the following problems:

1) We try to minimize unnecessary Experiments and reject those which re-implement already existing APIs.
findnow.getRawSubject() : - Please use getFull(messageId) to get access to the raw headers and use the subject from there (yes, that does include the &quot;Re:&quot;).

findnow.buildFilename():
- why does that need to be an Experiment? What stops you from doing this in WebExtension code directly? You can get the date from the header. Instead of the messagekey you could use the headerMessageId.
findnow.saveTo(): - everything that involves getting the raw message should use getRaw(). In 115 you can also get the content as a DOM File object via getRaw(messageId, {data_format: &quot;File&quot;}) (not yet documented, see https://searchfox.org/comm-esr115/rev/d32fefb23a6afce4c7f71af10978fa1c3064edf1/mail/components/extensions/parent/ext-messages.js#757).
- when saving files, it is highly suggested to use the downloads API and prompt the user to pick the file save location and not use an Experiment that saves in the background unnoticed

- findnow.pickPath / joinPath / exist Path : I assume these would all be obsolete, if the downloads API is used,

This would make your add-on a pure WebExtension which should be a top priority goal. From the feedback we get from users, they really do not want to grant the &quot;Full access to my computer&quot; permission anymore.

It is true that the look and feel - specially using the downloads API - could be a bit different, but it is definitely worth the gain to not having to update the add-on for a future version of Thunderbird.

Rejecting this due to findnow.getRawSubject() and manually streaming messages. But please consider the other alternatives as well. Feel free to reach out for further discussions:

- https://developer.thunderbird.net/add-ons/community
- [john@thunderbird.net](mailto:john@thunderbird.net)

This version of your add-on has been disabled. You may re-request review by addressing the reviewer's comments and uploading a new version at https://addons.thunderbird.net/de/developers/addon/findnow2/versions

********
Developer Resources
********

To respond, please reply to this email or visit: https://addons.thunderbird.net/de/developers/addon/findnow2/versions

You can also get in touch with the Thunderbird Add-on Reviewer Team via Matrix at https://chat.mozilla.org/#/room/#tb-addon-reviewers:mozilla.org or by Emailing us at: [Tb-addon-reviewers@lists.thunderbird.net](mailto:Tb-addon-reviewers@lists.thunderbird.net)

For more information about the review process and policies, please visit https://thundernest.github.io/atn-review-policy/

**Comment by stefanwerfling** [comment]
Hi Stefan,

if an add-on needs functionality that is not available through existing WebExtension APIs, then it can use Experiments. We do try to point to alternatives, but if they do not meet the requirements, then we do not reject those Experiments.

Your add-on was rejected because of findnow.getRawSubject() and manually streaming messages. The downloads API as an alternative for your Experiments related to the filePicker, was a suggestion.

You are correct, that the downloads API does not allow specifying the folder, it should point to initially. I think it opens the last used folder. If your client needs that feature, then you do have to re-implement it.

Sorry for not responding directly to your message.

All the best,
John

**Comment by Choppel** [comment]
Will be "tested" by John. If he accepts the plugin than this issue can be close.

**Comment by Choppel** [comment]
John Bieling wrote:

This is now good to be released. There is one thing I would like you to remove before this goes into production: The startup event. There is an "events" entry in your manifest.json in the "experiments_api" property, and a "onStartup" function in your implementations file.

Both can be removed.

a) You are not using the registered chrome path, it would look like ["chrome://findnow/content/..."](chrome://findnow/content/...)
b) You are not destructing the registered handle on shutdown via chromeHandle.destruct(), which may cause issues if your add-on is disabled and re-enabled.

**Comment by Choppel** [comment]
Published version 3.5 to thunderbird addons.
