### ISSUE TITLE
Store button does not work without a default directory

### ISSUE THREAD

**Issue by Choppel** [OpenSourcePKG/findnow_tbplugin#31]
If no default directory is selected in the settings, or it is invalid, then nothing comes up when you click the "Store" button.

**Comment by stefanwerfling** [comment]
Fix the path building, if has wrong check. 
- > 
- Test1: With default directory.
- Test2: Without default directory.

Directory Pick now every show by empty path. When user cancel and path is again empty, cancel save process.
