### ISSUE TITLE
Feedback for a fs API for Thunderbird.

### ISSUE THREAD

**Issue by jobisoft** [OpenSourcePKG/findnow_tbplugin#34]
This is far from being a thing. I just want to make sure that I cover your use case with this proposal. I have no idea if we can move this forward at all.

https://docs.google.com/document/d/1Ia322Epy-k0GGMaisSPaPVVF-WYhCWER5IE3HCfPF3U/edit?usp=sharing

Discussion in this issue, if that is fine with you.

IIRC, you have the filepicker Experiment in your add-on, because you need to preselect the download location. With the proposed fs API you could have a button in your options page to select a default download location

```
let standardFolderHandle = await browser.fs.showDirectoryPicker({
   startIn: "documents",
   permission: "startIn",
})
```

and then use that handle whenever you need to store a file

```
let fileHandle = await browser.fs.showSaveFilePicker({
   startIn: standardFolderHandle.fsFolderId,
   permission: "writeOnce",
})
await browser.fs.setFile(fileHandle.fsFileId, file)
```

This would prompt the user each time you want to save a file and the file picker will open the folder specified in your options.

None of these filePickers is requesting a permanent permission and therefore do not prompt the user for additional access permissions. But you *could* request permanent permissions, and then you would not need to ask the user where to store files, but simply use the folder specified in your options. Do not know if that is a use case for you at all.

**Comment by Choppel** [comment]
Hi John,

the approach #2 in the proposal seems promising. AFAICT it would cover our use case.

regards Stefan
