### ISSUE TITLE
Update 128 ESR

### ISSUE THREAD

**Issue by stefanwerfling** [OpenSourcePKG/findnow_tbplugin#35]
We must change the API for FilePicker.

![image](https://github.com/user-attachments/assets/b69a0e88-25d5-423d-ba1f-2b56445642fe)

**Comment by stefanwerfling** [comment]
https://developer.thunderbird.net/add-ons/updating/tb128#esmification

**Comment by stefanwerfling** [comment]
@Choppel 
We now have to test the new version again.

**Comment by Choppel** [comment]
Everything looks good. Closed for now. Next test is with 128.1 or 128.2.
