### ISSUE TITLE
Wrong filename is used

### ISSUE THREAD

**Issue by Choppel** [OpenSourcePKG/findnow_tbplugin#9]
Storing a file results in a new subdirectory being created with the name of the mail. Inside this directory is a file called test.eml.

**Comment by stefanwerfling** [comment]
That was only the case at the beginning and has already been patched.

**Comment by Choppel** [comment]
Still occurs. Forgot to commit and push?

**Comment by stefanwerfling** [comment]
If I wanted to mention the issues in the commit, I have imported the current status, you can now test it.
